### ISSUE TITLE
Crashes on Linux and Windows

### ISSUE THREAD

**Issue by prensing** [rusq/slackdump#240]
**Describe the bug**
I tried the latest 2.4.3 on both Windows and Linux (latest version of Mint), and both crash in the browser as I am trying to authenticate.
I also tried 2.4.2 on Linux, but Slack will not allow that browser to log in (too old).

**Output**
Crash backtrace:
```./slackdump -u
Slackdump 2.4.3 (commit: ef85584f863e6cb20c036aa672394fbdadc8b88f) built on: 2023-10-06T23:14:55Z
? Enter Slack Workspace Name:  xxx
Please login in the browser...
BEWARE: your OS is not officially supported by Playwright; downloading fallback build.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x82ba3c]

goroutine 1 [running]:
github.com/rusq/slackdump/v2/auth/browser.extractToken({0x0, 0x0})
	/home/runner/work/slackdump/slackdump/auth/browser/extractors.go:29 +0x1c
github.com/rusq/slackdump/v2/auth/browser.(*Client).Authenticate(0xc0000220c0, {0xa74248?, 0xc0001487e0?})
	/home/runner/work/slackdump/slackdump/auth/browser/client.go:119 +0x911
github.com/rusq/slackdump/v2/auth.NewBrowserAuth({0xa74248, 0xc0001487e0}, {0xc0001292e8, 0x2, 0xc0000061a0?})
	/home/runner/work/slackdump/slackdump/auth/browser.go:62 +0x365
github.com/rusq/slackdump/v2/internal/app.SlackCreds.AuthProvider({{0x0?, 0x8f1ca0?}, {0x0?, 0x7b0052?}}, {0xa74248, 0xc0001487e0}, {0x0, 0x0}, 0x0)
	/home/runner/work/slackdump/slackdump/internal/app/auth.go:77 +0x185
github.com/rusq/slackdump/v2/internal/app.InitProvider({0xa74248?, 0xc0001487b0?}, {0xc000104360, 0x1f}, {0x0, 0x0}, {0xa72580, 0xc0000ba700}, 0xc0000ade60?)
	/home/runner/work/slackdump/slackdump/internal/app/auth.go:149 +0x310
main.run({_, _}, {{{0x1, 0x0}, {0xc0000ade60}, {{0xa6c398, 0x1}, {0x98fdde, 0x4}, {0x0, ...}}, ...}, ...})
	/home/runner/work/slackdump/slackdump/cmd/slackdump/main.go:135 +0x20d
main.main()
	/home/runner/work/slackdump/slackdump/cmd/slackdump/main.go:106 +0x566
```

**Desktop (please complete the following information):**
 - OS: Linux Mint or Windows-10

**Comment by rusq** [comment]
Hi @prensing , thanks for the report, I'm already working on a fix.

Is your Slack workspace using SSO? If yes, what SSO provider?  I had reports that it breaks with Okta.

**Comment by rusq** [comment]
There were several problems that were fixed.  The problems cascade was this:
- short timeout (user was given 30 seconds to login), that caused
- the login page to be closed before user was able to complete the login.  Even if user was able to login within 30 seconds, it wasn't enough for the browser auth to finish waiting for the desired request, and capture the login cookies.  Additionally,
- the panic was caused by not handling the error returned by the new APIs (playwright-go API changed a bit with update, and the error wasn't handled properly).

Once #241 is merged, I'll publish the patch (v2.4.4)
