### ISSUE TITLE
Panics on 2GB+ ZIP archives

### ISSUE THREAD

**Issue by rusq** [rusq/slackdump#93]
**Describe the bug**
v2.0.2 Panics on huge archives in `bufio.go`
```
bufio.(*Writer).Flush(0xc00007e000)
	/usr/local/Cellar/go/1.18.3/libexec/src/bufio/bufio.go:634 +0x171
```

Archive size:
```
-rw-r--r--  1 rustam  staff  2376101723 21 Jul 21:51 test.zip
```

**To Reproduce**
1. `go run ./cmd/slackdump -f -export 'test.zip' https://x.slack.com/archives/x`

**Expected behavior**

**Output**

```
2022/07/21 21:51:14 file "x.png" saved to random/attachments: 555722 bytes written
panic: runtime error: slice bounds out of range [:4201] with capacity 4096

goroutine 56 [running]:
bufio.(*Writer).Flush(0xc00007e000)
	/usr/local/Cellar/go/1.18.3/libexec/src/bufio/bufio.go:634 +0x171
bufio.(*Writer).Write(0xc00007e000, {0xc00a940200?, 0x0?, 0xc0024578e0?})
	/usr/local/Cellar/go/1.18.3/libexec/src/bufio/bufio.go:672 +0xd8
archive/zip.(*countWriter).Write(0xc0001282a0, {0xc00a940200?, 0x7?, 0x2?})
	/usr/local/Cellar/go/1.18.3/libexec/src/archive/zip/writer.go:601 +0x2e
archive/zip.(*countWriter).Write(0xc00026e108, {0xc00a940200?, 0xc002620420?, 0xc002620450?})
	/usr/local/Cellar/go/1.18.3/libexec/src/archive/zip/writer.go:601 +0x2e
compress/flate.(*huffmanBitWriter).write(...)
	/usr/local/Cellar/go/1.18.3/libexec/src/compress/flate/huffman_bit_writer.go:136
compress/flate.(*huffmanBitWriter).writeCode(0xc00a9401e0?, {0xe180?, 0x5ca?})
	/usr/local/Cellar/go/1.18.3/libexec/src/compress/flate/huffman_bit_writer.go:347 +0xe5
compress/flate.(*huffmanBitWriter).writeTokens(0xc00a9401e0, {0xc00e828000, 0x4001, 0x2d541400?}, {0xc00a930d80, 0x11e, 0x100ea1d?}, {0xc005cae280, 0x1e, 0x1e})
	/usr/local/Cellar/go/1.18.3/libexec/src/compress/flate/huffman_bit_writer.go:583 +0xb9
compress/flate.(*huffmanBitWriter).writeBlock(0xc00a9401e0, {0xc00e828000?, 0x20?, 0xffffffffffffc090?}, 0x0, {0xc00cdf0000, 0x4090, 0x10000})
	/usr/local/Cellar/go/1.18.3/libexec/src/compress/flate/huffman_bit_writer.go:495 +0x490
compress/flate.(*compressor).writeBlock(0xc00e786000, {0xc00e828000?, 0x10fced5?, 0x30?}, 0x0?)
	/usr/local/Cellar/go/1.18.3/libexec/src/compress/flate/deflate.go:170 +0x9c
compress/flate.(*compressor).deflate(0xc00e786000)
	/usr/local/Cellar/go/1.18.3/libexec/src/compress/flate/deflate.go:509 +0x59b
compress/flate.(*compressor).write(0xc00e786000, {0xc00e6f0000?, 0x14ed6, 0xca414fff?})
	/usr/local/Cellar/go/1.18.3/libexec/src/compress/flate/deflate.go:554 +0x82
compress/flate.(*Writer).Write(...)
	/usr/local/Cellar/go/1.18.3/libexec/src/compress/flate/deflate.go:712
archive/zip.(*pooledFlateWriter).Write(0xc0007437d0?, {0xc00e6f0000?, 0x14ed6?, 0xc002457c28?})
	/usr/local/Cellar/go/1.18.3/libexec/src/archive/zip/register.go:51 +0xc5
archive/zip.(*countWriter).Write(...)
	/usr/local/Cellar/go/1.18.3/libexec/src/archive/zip/writer.go:601
archive/zip.(*fileWriter).Write(0xc000020370, {0xc00e6f0000, 0x14ed6, 0x1fe00})
	/usr/local/Cellar/go/1.18.3/libexec/src/archive/zip/writer.go:533 +0x97
bytes.(*Reader).WriteTo(0xc000358810, {0x15b9800?, 0xc000020370?})
	/usr/local/Cellar/go/1.18.3/libexec/src/bytes/reader.go:144 +0x87
io.copyBuffer({0x15b9800, 0xc000020370}, {0x15b98a0, 0xc000358810}, {0x0, 0x0, 0x0})
	/usr/local/Cellar/go/1.18.3/libexec/src/io/io.go:408 +0x16e
io.Copy(...)
	/usr/local/Cellar/go/1.18.3/libexec/src/io/io.go:385
github.com/rusq/slackdump/v2/fsadapter.(*ZIP).WriteFile(0x15bcfc8?, {0xc006bae000?, 0x27?}, {0xc00e6f0000, 0x14ed6, 0x1fe00}, 0x2457dc8?)
	/Users/rusq/gdrive/dev/go/github.com/rusq/slackdump/fsadapter/zipfs.go:64 +0x178
github.com/rusq/slackdump/v2/downloader.(*Client).saveFile(0xc000120070, {0x15bcfc8, 0xc00011c090}, {0xc0009d0810, 0x12}, 0xc005055200)
	/Users/rusq/gdrive/dev/go/github.com/rusq/slackdump/downloader/downloader.go:238 +0x270
github.com/rusq/slackdump/v2/downloader.(*Client).worker(0xc000120070, {0x15bcfc8, 0xc00011c090}, 0xc000176000)
	/Users/rusq/gdrive/dev/go/github.com/rusq/slackdump/downloader/downloader.go:176 +0x309
github.com/rusq/slackdump/v2/downloader.(*Client).startWorkers.func1(0x0?)
	/Users/rusq/gdrive/dev/go/github.com/rusq/slackdump/downloader/downloader.go:155 +0x65
created by github.com/rusq/slackdump/v2/downloader.(*Client).startWorkers
	/Users/rusq/gdrive/dev/go/github.com/rusq/slackdump/downloader/downloader.go:154 +0x65
exit status 2
```

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**

**Comment by rusq** [comment]
Until this is fixed, use `-export dir` or `-base dir` parameter for large exports (as opposed to "-export file.zip" or "-base file.zip")
