### ISSUE TITLE
AttributeError when opening export with slack-export-viewer

### ISSUE THREAD

**Issue by sjuneja09** [rusq/slackdump#97]
I just setup slackdump and slack-export-viewer today. The export was successful but when I try to open it with the viewer, it errored out with an AttributeError. Any ideas about this? 

20220728.zip extracting to /var/folders/9q/nm0mln8j3m38fk8621xn7l580000gn/T/_slackviewer/4ccc26e8ef2c6b952e48cbe2c3639cc1aa885400...
20220728.zip extracted to /var/folders/9q/nm0mln8j3m38fk8621xn7l580000gn/T/_slackviewer/4ccc26e8ef2c6b952e48cbe2c3639cc1aa885400
Traceback (most recent call last):
  File "/Users/sjuneja/.pyenv/versions/3.9.4/bin/slack-export-viewer", line 33, in <module>
    sys.exit(load_entry_point('slack-export-viewer==1.1.4', 'console_scripts', 'slack-export-viewer')())
  File "/Users/sjuneja/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sjuneja/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/sjuneja/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sjuneja/.pyenv/versions/3.9.4/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/sjuneja/.pyenv/versions/3.9.4/lib/python3.9/site-packages/slackviewer/main.py", line 61, in main
    configure_app(app, archive, channels, no_sidebar, no_external_references, debug)
  File "/Users/sjuneja/.pyenv/versions/3.9.4/lib/python3.9/site-packages/slackviewer/main.py", line 24, in configure_app
    top.channels = reader.compile_channels(channels)
AttributeError: 'LocalStack' object has no attribute 'channels'

**Comment by rusq** [comment]
This looks like slack-export-viewer issue: https://github.com/hfaran/slack-export-viewer/issues/157

**Comment by sjuneja09** [comment]
Thanks for the pointer, the resolution there fixed it!
